### ISSUE TITLE
Wish: -q / --quiet mode to support all output except hours

### ISSUE THREAD

**Issue by markstos** [pvdlg/ncat#66]
It would be nice to have the option to only see output if there's an error. 

There's enough output for me know that if there was an error, it might be lost in the scrollback. 

Thanks.

**Comment by pvdlg** [comment]
What would be the benefit of that feature? In which case would it be useful?
You mention that an error might be lost in the scrollback, but how having no output at all could be clearer?

**Comment by markstos** [comment]
I would like to incorporate ncat into a complex build process. I only need to see the summary of what happened unless there is an error.

However, there is a workaround if the information messages are written to STDOUT while errors are written to STDERR. I could redirect the STDOUT to /dev/null while making sure STDERR is still displayed.

**Comment by pvdlg** [comment]
> I would like to incorporate ncat into a complex build process. I only need to see the summary of what happened unless there is an error.

But why? What difference does it make to log?

If you use the `--output` option the concatenated files will be written to the file in argument, if you don't set that option, the concatenated files are written to the `stdout`, without logging.
If you want to know if an error happened, you can check the exit code.

**Comment by markstos** [comment]
Because seeing the summary of where I am in the build process is useful.   I could see that I'm currently in the "concat" step I have completed 6 of 8 steps. 

When instead I see a list of files flying by, I lose the context of the big picture. 

As you see, there is a workaround of concat'ing the files to STDOUT, then redirecting STDOUT to a file, which is what I'll do.

Thanks for the tip!

**Comment by pvdlg** [comment]
I think concatenating to stdout and redirect to a file is the right solution. I'll close this then.
